title: daichi.dev
description: >-
  プログラミングや日々開発してる上で感じた事、日常について書いています。
url: https://daichi.dev

timezone: Asia/Tokyo
lang: ja_JP

plugins:
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-auto-image

postcss:
  cache: false

defaults:
  - scope:
      type: posts
    values:
      layout: posts
      permalink: /posts/:year-:month-:day-:title
  - scope:
      type: drafts
    values:
      layout: posts
      permalink: /posts/:year-:month-:day-:title

exclude:
  - Makefile
  - CNAME
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

image: /assets/images/og.png

